### PR TITLE
limit message batches by size of serialized payload

### PR DESCRIPTION
**Pull request by achille-roussel**
@f2prateek 

Changes related to limiting message batches to 500KB as described in #84

### CODE REVIEW

**Comment by f2prateek** [comment]
This feels wasteful that  we marshal a message twice - once for length, and once for an upload.

**Comment by achille-roussel** [comment]
I don't think this is what the code is doing, the marshaled JSON is cached in the `message` object which implemented `json.Marshaler` and just returns the value it has cached instead of re-marshaling.

See: https://github.com/segmentio/analytics-go/pull/86/files#diff-b95c50d14ed7b4bb1cfecdc4e498d4dcR67

**Comment by f2prateek** [comment]
Ah I see, nice! Seeing `json.Marshal` twice confused me.

**Comment by achille-roussel** [comment]
:) `json.Marshaler` is a sexy pretty sexy way of injecting stuff in the JSON encoder.

Let me know if that's good to go.

**Comment by f2prateek** [comment]
LGTM!

**Pull request merged**
